### ISSUE TITLE
recently I got error  "pushbullet_pro_required" on send note

### ISSUE THREAD

**Issue by Megido6** [randomchars/pushbullet.py#101]
wtf?
all functions now need fee?

**Comment by Megido6** [comment]
i need pay for laggy program?  i use better  a telegram bot

**Comment by simonporter007** [comment]
Presumably you hit the rate limit which is stated in their developer API  docs. "Push limit
Free accounts (without a Pro subscription) are limited to 500 pushes per month. Going over will result in an error when sending a Push."

**Comment by bil-elmoussaoui** [comment]
@Megido6 how did you receive that message?
I think pushbullet.py should implement an exception for that so it can be detected easily by the user instead  of showing the message directly.
