### ISSUE TITLE
Asyncio Version

### ISSUE THREAD

**Issue by rharder** [randomchars/pushbullet.py#110]
I made an asyncio-based version of the randomchars/pushbullet.py code.  To minimize duplication of code between the synchronous and asynchronous version, I replumbed a good bit of the original Pushbullet class, keeping all the pre/post processing around http calls in one place.  Otherwise I tried to isolate my changes to minimize impact on Python v2.7 users.

Except I can't seem to get even the original code to work on v2.7 either.  I wonder if some supporting packages changed since the original creation.

So...not sure if original author is interested in merging my code back into the randomchars version that's already registered with pip.  For the sake of the Python community I'd sure like to avoid yet another similarly-named package in pip.

Here's my repo: https://github.com/rharder/pushbullet.py

I haven't begun a formal pull request until I hear from the original author.

-Rob

**Comment by rharder** [comment]
Haven't heard from "randomchars" yet.  I can't seem to get the originaly pushbullet.py package to work under Python 2.7 anyway.  Something about ssl errors.  I think I might more forward with making something like an "async_pushbullet" pypi package.  Will wait a while in case there's a better idea.

**Comment by kovacsbalu** [comment]
If someone needs this good stuff: `pip install asyncpushbullet`
