### ISSUE TITLE
requests.exceptions.SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by Animal79** [randomchars/pushbullet.py#112]
I've installed it on raspberry pi and I receive this error 
requests.exceptions.SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol
when I try 
pb = Pushbullet(api_key)
Could someone help me?

Thanks,
Carmine

**Comment by simonporter007** [comment]
Seems same as issue #103 and #106 can you please try upgrading openssl and pyOpenSSL libraries as described there? It resolved the issue for the original posters.

**Comment by kovacsbalu** [comment]
@Animal79 pyOpenSSL-0.13 fixed my problem
