### ISSUE TITLE
0.11 missing on pypi

### ISSUE THREAD

**Issue by Danielhiversen** [randomchars/pushbullet.py#116]
It would be great if you add the latest version to pypi.

**Comment by kiike** [comment]
ping @randomchars, @r-darwish ;)

**Comment by r-darwish** [comment]
Sorry, but stopped using PushBullet a few months ago

**Comment by kiike** [comment]
No problem @r-darwish! Take care.

**Comment by kovacsbalu** [comment]
@Danielhiversen, @kiike Now available on PyPI
