### ISSUE TITLE
push_list raises PushError("The param 'type' has an invalid value.")

### ISSUE THREAD

**Issue by MrGreenTea** [randomchars/pushbullet.py#117]
I wanted to try pushing a list and tried the example from the pypi page:
```
to_buy = ["milk", "bread", "cider"]
pushbullet.push_list('Shopping list', to_buy)
```
But i get the following error message:
```PushError: {"error":{"code":"invalid_param","type":"invalid_request","message":"The param 'type' has an invalid value.","param":"type","cat":"\u003e:3"},"error_code":"invalid_param"}```

What am I doing wrong? All other pushes work fine.
I am using version 0.10.0.

**Comment by MrGreenTea** [comment]
I just tested pushing an address and that raises the same Error. Do I need Pro or something for it to work?

**Comment by simonporter007** [comment]
This was removed from Pushbullet API: "January 28, 2015

• Removed address and list pushes which have been deprecated for forever."

It was removed in pushbullet.py a while back too. I think 0.11 was released if you can upgrade or take it direct from master branch after checking out with git.

**Comment by MrGreenTea** [comment]
I see and that makes sense too. Is there a reason why 0.11 isn't on pypi?

**Comment by troeggla** [comment]
No, not really. I don't have direct access to PyPi, but Travis seems to be configured to publish to PyPi if a new tag gets published, but last time I did that nothing happened. Not quite sure what's going on there. If anyone has more experience with this, can they maybe look into it?
