### ISSUE TITLE
requests.exceptions.SSLError

### ISSUE THREAD

**Issue by JeffWScott** [randomchars/pushbullet.py#125]
all I have is this code:
from pushbullet import Pushbullet
pb = Pushbullet('oNOTMYREALAPICODEAiZ4F')

and it's enought to generate this error:
requests.exceptions.SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

**Comment by kovacsbalu** [comment]
Hi @JeffWScott , did you see #112 ?

**Comment by JeffWScott** [comment]
Thanks for the reply i will give that a shot.

**Comment by JeffWScott** [comment]
I updated both (openssl was the latest) and now i get this.

/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "notification.py", line 8, in <module>
    devices = p.getDevices()

**Comment by JeffWScott** [comment]
I just want to add I appreciate any help, I'm not great at this stuff, but I need this to work :)

**Comment by kovacsbalu** [comment]
You can disable this warning as described on the url: [https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings](url)

**Comment by JeffWScott** [comment]
Looks like that site is telling me to update python to 2.7.9.  I have 2.7.6.

**Comment by JeffWScott** [comment]
Installed 2.7.14.
Works perfectly now.

Thanks so much!
