### ISSUE TITLE
failure to retreive list of devices

### ISSUE THREAD

**Issue by mjaga** [randomchars/pushbullet.py#17]
I can retrieve my list of devices like so from the command line:
curl -u key : https://api.pushbullet.com/v2/devices 
and I can see that I have two devices with "active":false settings before my active devices. It turns out that pushbullet.py does not seem able to list my devices but returns "tuple index out of range". 

from pushbullet import PushBullet
pb = PushBullet(key)
print pb.devices

However, with the yapbl package (and basically the same syntax) this works flawlessly.

**Comment by rfrezende** [comment]
Hi there,

To solve this bug I modified the file pushbullet.py as follows:

```python
@@ -34,12 +34,13 @@ class PushBullet(object):
         resp = self._session.get(self.DEVICES_URL)
         resp_dict = resp.json()
         device_list = resp_dict.get("devices", [])
 
         for device_info in device_list:
-            d = Device(self, device_info)
-            self.devices.append(d)
+            if device_info.get("active"):
+                d = Device(self, device_info)
+                self.devices.append(d)
```

Have a happy new year.
