### ISSUE TITLE
Validation of API key

### ISSUE THREAD

**Issue by balloob** [randomchars/pushbullet.py#23]
`_load_devices`, `_load_contacts` and `_load_user_info` all fail gracefully if the API key is wrong. It would be great if something would blow up so I can notify my users.

**Comment by troeggla** [comment]
In my fork I have this fixed by throwing an exception if the API returns with status 401 (see commit 7b071b54f2153e5782ea6d52557fff576975f0ba). I'm waiting for the owner to accept a previous pull request until I can submit the feature as a new one.

**Comment by randomchars** [comment]
Fixed in 7b071b54f2153e5782ea6d52557fff576975f0ba
