### ISSUE TITLE
Use exceptions instead of returning tuples

### ISSUE THREAD

**Issue by r-darwish** [randomchars/pushbullet.py#24]
Returning a success boolean in a tuple is a pattern mostly used by Go developers, not Python. I think that the library should raise exceptions on errors, and the exceptions should contain information about the failure. I don't mind writing the pull request by myself if the author is OK with this suggestion.

**Comment by randomchars** [comment]
Frankly I have no idea why I wrote I like that. I've created a few exceptions and replaced all instances of this pattern with them in ba0c140619ba32046f78ce50a4d5ec0e0902e11b Is this what you had in mind?

**Comment by r-darwish** [comment]
Looking good. The examples in the documentation should be changed as well

**Comment by randomchars** [comment]
I've updated the documentation to reflect the changes.
