### ISSUE TITLE
Event-loop to receive events

### ISSUE THREAD

**Issue by Thor77** [randomchars/pushbullet.py#40]
Whats about some kind of event-loop with the possibility to register functions to receive incoming pushes?

**Comment by rharder** [comment]
I added receiving to a java implementation when I needed it (https://github.com/rharder/jpushbullet2).  That turned out pretty good.  I'd be happy to work on an asyncio addition to this library and submit a pull request if I pull if off. -Rob

**Comment by rharder** [comment]
Scratch that.  I see someone implemented it with a thread instead of asyncio.  That'll make python2 folks happier. =)
