### ISSUE TITLE
Readme doesn't reflect actual structure of Pushbullet.get_pushes() return value

### ISSUE THREAD

**Issue by obskyr** [randomchars/pushbullet.py#41]
The readme suggests that `Pushbullet.get_pushes()` returns a list of pushes. This is not true, however. It actually returns a two-length tuple, in which the first element is `True` and the second is the list of pushes.

Eg. the function currently returns:

```python
>>>pb.get_pushes()
(True, [push0, push1, push2])
```

Instead of:

```python
>>>pb.get_pushes()
[push0, push1, push2]
```

Simply updating the readme to reflect this (or changing the behavior of the function) would fix this. Some documentation of what the `True` means would be nice, too.

**Comment by r-darwish** [comment]
I think this can be closed now

**Comment by obskyr** [comment]
Ah, yes, indeed it can. Pull request #43 fixed it. Thanks!
