### ISSUE TITLE
Please appoint additonal project collaborators

### ISSUE THREAD

**Issue by r-darwish** [randomchars/pushbullet.py#54]
There are several pull requests and open issues which haven't been dealt with for a while. In order to keep this good library relevant, please appoint additional project collaborators.

**Comment by randomchars** [comment]
Sorry, I've neglected this project for quite a while now, as I've stopped using pushbullet for anything more than sending links to myself.
Would you be interested in taking over? I'm not sure how that should be done (organization or transferring this repo to someone else)

Also pinging @troeggla and @kovacsbalu as they have a few commits here as well. Any of you want to take over this project?

**Comment by kovacsbalu** [comment]
Hi, why not?!
I do not know either how it could take over, but let see. :)

**Comment by r-darwish** [comment]
I'd be happy to help. First, you should choose who'll own the repository and transfer the ownership to him using the settings menu. Then, the owner should appoint the others as collaborators. You should also appoint new owners in PyPi

**Comment by troeggla** [comment]
I'd also be more than happy to help you guys out on this thing! We plan to use Pushbullet as part of the error notification system on our servers, so this project is very useful to me.

**Comment by r-darwish** [comment]
@randomchars - sorry for nagging, but as it seems that the 3 of us are interested in helping, could you appoint all of us as collaborators?

**Comment by randomchars** [comment]
Sorry for the delay. I've added you all as collaborators.

**Comment by r-darwish** [comment]
Thanks!
