### ISSUE TITLE
Removing old versions from PyPi

### ISSUE THREAD

**Issue by balloob** [randomchars/pushbullet.py#55]
First off, thanks for making Pushbullet.py, it's awesome.

At [Home Assistant](https://home-assistant.io) we were depending on PushBullet.py 0.7.1 as we had no time yet to upgrade to the latest version. Somehow version 0.7.1 has gone missing from PyPi resulting in an error when people tried to install PushBullet support in Home Assistant.

I don't know if you had a role in removing the version from PyPi. But if you did, could you please be aware in the future that there are probably other projects depending on older versions of your code, thanks!

**Comment by r-darwish** [comment]
Since when did it start happening? I just upload version 0.9.0 but I did not delete any old version.

**Comment by balloob** [comment]
We got the first report 3 days ago: balloob/home-assistant#594

**Comment by r-darwish** [comment]
If you have not upgraded yet I may be able to re-upload 0.7.1. I'll check if PyPi has some sort of automatic package removal

**Comment by balloob** [comment]
We have upgraded to 0.8.1 in our development branch. We should release it
within a week so I'm not too worried.

On Tue, Nov 10, 2015 at 12:27 PM, Roey Darwish Dror <
notifications@github.com> wrote:

> If you have not upgraded yet I may be able to re-upload 0.7.1. I'll check
> if PyPi has some sort of automatic package removal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/randomchars/pushbullet.py/issues/55#issuecomment-155555837>
> .
>



-- 
PaulusSchoutsen.nl
It's nice to be important but it's more important to be nice.
