### ISSUE TITLE
Possibly out of date information in README

### ISSUE THREAD

**Issue by iLoveTux** [randomchars/pushbullet.py#56]
I may very well be wrong, but [this section](https://github.com/randomchars/pushbullet.py#sending-sms-messages) of your README, dealing with sending SMS states `This is untested and uses an undocumented API. Use with caution.`, but I see [this section](https://docs.pushbullet.com/#send-sms) of the pushbullet's API documentation shows how to send SMS.

After reviewing your code in `pushbullet/pushbullet.py` line 259-275:

```python
    def push_sms(self, device, number, message):
        data = {
            "type": "push",
            "push": {
                "type": "messaging_extension_reply",
                "package_name": "com.pushbullet.android",
                "source_user_iden": self.user_info['iden'],
                "target_device_iden": device.device_iden,
                "conversation_iden": number,
                "message": message
            }
        }

        r = self._session.post(self.EPHEMERALS_URL, data=json.dumps(data))
        if r.status_code == requests.codes.ok:
            return r.json()
        raise PushError(r.text)
```

It seams as though you are following their documentation to the letter.

Perhaps simply an update to the README is in order, because as far as I can tell, you are correctly using their documented API.

**Comment by r-darwish** [comment]
Fixed in f8e2ed6. Thanks
