### ISSUE TITLE
Python 2.6 policy

### ISSUE THREAD

**Issue by r-darwish** [randomchars/pushbullet.py#60]
@randomchars, @troeggla, @kovacsbalu 

Currently we have no explicit policy regarding Python 2.6 so I think we should vote whether we want to support it or not. If the voting results in a positive answer then we need to add Python 2.6 to Travis and make sure we avoid using language features that aren't compatible with Python 2.6.

My personal opinion is against. Python 2.6 is a rather old version which lacks support of useful features such as dict/set comprehension and multiple context manager (without the use of the `nested` function). AFAIK it's being used only on CentOS 6. CentOS 6 is also quite an old distribution, although it's considered to be supported until 2020. Personally, I don't think we should support everything that Redhat supports. I also do not support Python 2.6 in [pushbullet-cli](https://github.com/r-darwish/pushbullet-cli).

Please cast your vote.

**Comment by kovacsbalu** [comment]
Hi @r-darwish,
you are right. As I know Python 2.6 reached its end-of-life in 2013 October. I found some tutorial how to install python 2.7 on Centos 6 [here](https://github.com/h2oai/h2o-2/wiki/Installing-python-2.7-on-centos-6.3.-Follow-this-sequence-exactly-for-centos-machine-only) and [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4) so, probably these could help Centos 6 pushbullet.py users.
My vote is: do not support python 2.6

**Comment by troeggla** [comment]
This may not be representative, but according to [this](http://www.randalolson.com/wp-content/uploads/python-survey-2014-versions-regularly-use.png) (it's from last year), 2.6 sees a usage share of less than 10% and I assume that it has dropped even more by now, if anything.

If maintaining support for Python 2.6 involves significant changes to the codebase going forward, negatively affects readability and/or understandability of the codebase, we might as well drop support for Python 2.6. My vote: Don't support 2.6

**Comment by r-darwish** [comment]
Well, that's 3 out of 4. Sorry @simonporter007, but we're dropping Python 2.6 support.

**Comment by simonporter007** [comment]
Ha! Well, that's good. Can take it back out of my tox test bed.
