### ISSUE TITLE
new_device() can be created without a nickname

### ISSUE THREAD

**Issue by simonporter007** [randomchars/pushbullet.py#65]
Found this during some unit testing I was practicing. Reading up about this, it appears the pythonic way is to allow this and leave it up to the user to correctly use the function with specified argument. However, at the moment it will cause failure further down the line as the `[IndexError("tuple index out of range") raised in repr()]` when it comes to try and print the device using the `__repr__` function.

I am not sure of the best or most welcome method to resolve this, so haven't submitted a pull request. I guess it's either making the nickname mandatory (not None) or adjusting the `__repr__` function to print nickname, manufacturer + model or a default?

**Comment by simonporter007** [comment]
Sorry, should also add that pushbullet allows blank nickname for a device, so it doesn't fail on server side. It simply gets added with no nickname, I wonder if the client should use iden instead in this case, which is pushbullet unique key.

**Comment by r-darwish** [comment]
Thanks for reporting
