### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 Applicatyion

### ISSUE THREAD

**Issue by Abolfazl** [randomchars/pushbullet.py#66]
I have an issue with Pushbullet.py and Python3.5. When I try to import the module, I get the following error. Is there a reason for this?

![image](https://cloud.githubusercontent.com/assets/116760/12560137/e22292c0-c34d-11e5-8b49-2152558dc401.png)

I have already run `pip install pushbullet.py --upgrade` and it did not work

**Comment by simonporter007** [comment]
What architecture is your python? According to libmagic python:

"'WindowsError: [Error 193] %1 is not a valid Win32 application': Attempting to run the 32-bit libmagic DLL in a 64-bit build of python will fail with this error. I'm not aware of any publically available 64-bit builds of libmagic. You'll either need to build them yourself (please share docs!), or switch to a 32-bit Python."

**Comment by Abolfazl** [comment]
I am not sure why but doing `pip install filemagic` fixed my issue.
