### ISSUE TITLE
Get pushes from specific device

### ISSUE THREAD

**Issue by the-new-sky** [randomchars/pushbullet.py#70]
Hello,
Here is a short question : _How i can get pushes from specific device ?_

**Comment by kovacsbalu** [comment]
Hi,
you can read pushes `pb.get_pushes()` and filter the specified device with `push.get("target_device_iden")`.
See `get_my_active_pushes()` function in [https://github.com/kovacsbalu/pushbullet-rpc/blob/master/pushbulletrpc/pushbulletrpc.py]

**Comment by the-new-sky** [comment]
Thank you for your answer.
