### ISSUE TITLE
Pushbullet doesn't stop sending sms

### ISSUE THREAD

**Issue by Murdocc007** [randomchars/pushbullet.py#75]
Hi I wrote a short script to test the sms feature. 

But it has kept on sending the same sms for last 1 hour. 

`from pushbullet import  PushBullet
pb=PushBullet('----')
print pb.devices

device=pb.devices[0]

push = pb.push_sms(device, "---", "Wowza!")`

**Comment by simonporter007** [comment]
I can't see why it would loop at all but I do notice you're using camel case in your import and class statements, which suggests you're on an older version of the code? The latest version should be:
``` python
from pushbullet import Pushbullet
pb=Pushbullet(API_KEY)
```
