### ISSUE TITLE
Devices does not have an icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [randomchars/pushbullet.py#81]
The devices icon value is always None

```
devices = pb.devices
print(devices[0].icon)

```

will return a NoneType exception

**Comment by simonporter007** [comment]
I guess this occurs on existing devices and not new devices created with pyshbullet py? Should be system by default on new devices. Will have to add the same in the devices constructor.

**Comment by bil-elmoussaoui** [comment]
@simonporter007 Yes :) Thanks!

**Comment by bil-elmoussaoui** [comment]
Why this have been closed ?

**Comment by kovacsbalu** [comment]
Because this fixed in c8fe677

**Comment by bil-elmoussaoui** [comment]
Well, the PR is not merged yet ;)

**Comment by kovacsbalu** [comment]
Whoops :)
Thanks for your notice

**Comment by bil-elmoussaoui** [comment]
You're welcome!
