### ISSUE TITLE
Push address does not work

### ISSUE THREAD

**Issue by Timvdv** [randomchars/pushbullet.py#86]
I tried pushing a address with the example code in the readme file

```
address = " 25 E 85th St, 10028 New York, NY"
push = pb.push_address("home", address)
```

This results in this error:

```
pushbullet.errors.PushError: {"error":{"code":"invalid_param","type":"invalid_request","message":"The param 'type' has an invalid value.","param":"type","cat":"\u003e:3"},"error_code":"invalid_param"}
```

the send note does work! So I'm sure the settings are right.

**Comment by kovacsbalu** [comment]
Hi @Timvdv,
I ran a unit test with your address and works correctly. Tomorrow I will test it via real Pushbullet service.

**Comment by kovacsbalu** [comment]
Well, "address" and "list" types was removed in api v15.
See change January 28, 2015: https://docs.pushbullet.com/#changelog
Thanks for your report.

**Comment by Timvdv** [comment]
@kovacsbalu Do you know if there is a replacement for showing an address? I was hoping for some kind of map view within Pushbullet, but I guess I'd just have to push the address as a note :(

**Comment by kovacsbalu** [comment]
I really don't know. :(
I will create a PR and show address and list type as deprecated.
